### ISSUE TITLE
Make pressing `enter` key save all create forms

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#1181]
## Problem to solve

_Is your feature request related to a problem? Provide a clear and concise
description of what the problem is. Ex. I'm always frustrated when [...]_

## Proposal

_Describe the feature/solution you'd like. A clear and concise description of
what you want to happen._

## More details

_Add any other notes or screenshots about the feature request here._

**Comment by midnight-madman** [comment]
Hi @johnnyd-eth - I'd love to solve this ticket.

Can you specify which forms are relevant here? And what is the expected save behaviour? Save in local storage or submit to create project?

I've roamed around the "Launch Project" flow and some already have the `enter` key to save/continue functionality.
Steps to re-create: visit https://juicebox.money/create, click in `Project name` field and press `enter` key.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/94986441/184543902-f831163e-2e93-416c-b1cd-332cebd66180.png">

Thanks! :)

**Comment by johnnyd-eth** [comment]
@NakedFool this still applies to new create flow. Whenever the 'Next' button is enabled, we should be able to press enter and go to the next tab. 

We also want to make sure each modal within the create flow can be confirmed by pressing enter, which I think a few can't.

Feel free to break this up into smaller PR's if you like and request me for review!

**Comment by NakedFool** [comment]
> @NakedFool this still applies to new create flow. Whenever the 'Next' button is enabled, we should be able to press enter and go to the next tab.
> 
> We also want to make sure each modal within the create flow can be confirmed by pressing enter, which I think a few can't.
> 
> Feel free to break this up into smaller PR's if you like and request me for review!

Closing this as not completed for now ser.

While I really like this feature, there was a discussion between Strath and me, and he suggested that we hold off on it for now since users could accidentally hit the keyboard buttons, leading them to the next step and potentially causing confusion in an already complex form. We decided to prioritize accessibility over responsibility for now.

Link to discussion https://discord.com/channels/939317843059679252/998806024163176490/1052125060158210068
