### ISSUE TITLE
Editing payouts from the "reconfigure" page. small bug

### ISSUE THREAD

**Issue by mejango** [jbx-protocol/juice-interface#119]
When I click to adjust a payout that goes to a project, I have to retype in the project's handle in to the UI.

![image](https://user-images.githubusercontent.com/77952627/132095463-f4c3ec74-6bb1-4a73-b62b-0e0b3310011c.png)

**Comment by peripheralist** [comment]
this is looking great, but i'm noticing the issue still remains when editing a payoutMod. the `initialValue` is undefined when it shouldn't be, so probably not a bug in your code. 

poking around a bit, it looks like an issue with how the `initialValue` is being passed from `ProjectPayoutMods`. if you wanna take a look at it you might be able to work in a fix with this PR, otherwise i'll start working on it separately later tonight
