### ISSUE TITLE
[4] Bad rendering of NFTs in pay modal

### ISSUE THREAD

**Issue by wraeth-eth** [jbx-protocol/juice-interface#3007]
## Summary

Adding too many NFTs causes the images to overflow off the element.

## Steps to reproduce

1. Go to a project offering NFTs
2. Add a large amount of NFTs to pay for
3. Go to pay modal
4. Experience error

## What is the expected _correct_ behavior?

NFTs should be encapsulated on element in a way that makes sense.

## Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/104132113/217972612-818ad912-2ebd-42ea-8549-760d94b77fe7.png)

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

RICE:
R – 2 //only affects a small group of users that a. add NFT's to projects and b. add lot's of NFT's
I – 1 //bug isn't blocking users from the function – just doesn't 'look' right
C – 2 //high confidence that it only affects small group and isn't blocking users
E – 1 //small, quick change

Score: 4

**Comment by wraeth-eth** [comment]
@strath-m @tjl-me any ideas of what you think is the best way to do this? I was thinking maybe a fixed length, scrollable window, similar to the add sticker modal, embedded in this popup

**Comment by strath-m** [comment]
If it's the same NFT I don't think we need to show it repeated multiple times like that. Maybe showing a number in the corner or something.  Something like this.

![Screen Shot 2023-02-10 at 10 58 45 am](https://user-images.githubusercontent.com/109319681/217989379-a1cdac4a-cd15-415c-ae14-c9b2a6d2f97d.png)

**Comment by tjl-me** [comment]
Have RICE'd this one up lads. Something to think about in future of both design and dev are states. @strath-m @aeolianeth @wraeth-eth:

1. Nothing state – How does the component render pre-activation (if applicable)
2. Loading – how does the component render while it's loading data
3. None – how does the component render with no data
4. One – how does the component render with 1 item
5. Some – how does the component render with a few items
6. Too many – how does the component render when there are more than expected items
7. Incorrect – what is the error state?
8. Correct – what is the success state?
9. Done – what happens when the user is done and dusted with the component action (if applicable)

These considerations can either be by design or by dev. For example, specifying states in the design, or limiting state outcomes in development (e.g. user can not add more than 10 NFT's)

@strath-m I usually have. It covers most of them and reduces time spent at design phase:
- An inline loading state
- A page loading state
Then design for:
- None
- One
- Too many
- Incorrect
