### ISSUE TITLE
Improve currency context 

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#643]
## Proposal

Currency context will simply map a currency string ('ETH' or 'USD') to the integer they use in the contracts (0, 1 or 2). Then throughout the app we can just use the strings everywhere, only using the currency context at the point we interact with the contracts, where we need the currency integer

**Comment by peripheralist** [comment]
Will this allow for 'ETH' and 'USD' to be strongly typed? Right now currency context allows accidentally misspelling `currencyEth` or `currencyUsd` since the object keys are just `string` type. I don't mind keeping the dictionary pattern, something like

```
const { currencies: { ETH, USD } } = useContext(CurrencyContext)
```

as long as `currencies` is typed, so that `{ currencies: { ETHH } }` would show an error
