### ISSUE TITLE
Text entry input on number slider is difficult

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juice-interface#91]
![image](https://user-images.githubusercontent.com/79433522/129926307-839d08c3-4508-4b74-9cb5-dc34e003f3ab.png)

Typing numbers is glitchy due to custom parsing/formatting and can emit the wrong value

**Comment by nnnnicholas** [comment]
+1 

On Brave on Ubuntu 20.04 percentages entered in Spending and Reserved Tokens modals emit incorrect values most of the time. Fewer clicks between spawning the modal and confirming the number appears to work better.

Behavior: enter 25%, click confirm, 2% was emitted.
Expected behavior: enter 25%, click confirm, 25% emitted.

**Comment by aeolianeth** [comment]
@peripheralist I'd like to take on this issue. I've reproduced using `@nnnnicholas`'s steps above
